package com.company;

import javax.xml.bind.SchemaOutputResolver;
import java.io.*;
import java.nio.charset.Charset;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Properties;
import java.util.Scanner;
import java.util.stream.Stream;

public class Main {

    public static void main(String[] args) throws FileNotFoundException, UnsupportedEncodingException {
        Generator g = new Generator();
        PrintWriter pw = new PrintWriter("inserty.txt", "UTF-8");

        g.nacitajMenaPriezviska();
        g.nacitajPav();
        g.nacitajDatumy();
        g.nacitajNazov();
        g.nacitajObdobie();
        g.nacitajUlice();

        System.out.println("DOMACNOST 1-2");

        System.out.println("Generovanie domacnosti");
        System.out.println(g.generujDomacnost());

        System.out.println("Generovanie osob");
        System.out.println(g.generujZenu("965103/8089"));
        System.out.println(g.generujMuza("910806/3107"));


        System.out.println("Generovanie PAV");
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());

        System.out.println("Generovanie SPAV");
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println("Generovanie dlhov");
        System.out.println(g.generujDlh());
        System.out.println(g.generujDlh());
        System.out.println("Generovanie pravidelnych platieb");
        System.out.println(g.generujTypPP());
        System.out.println(g.generujTypPP());
        System.out.println(g.generujTypPP());
        System.out.println(g.generujTypPP());

        System.out.println("DOMACNOST 2-5");
        System.out.println("Generovanie domacnosti");
        System.out.println(g.generujDomacnost());
        System.out.println("Generovanie osob");
        System.out.println(g.generujZenu("435208/911"));
        System.out.println(g.generujMuza("610407/1028"));
        System.out.println(g.generujZenu("905313/3441"));
        System.out.println(g.generujMuza("960227/9599"));
        System.out.println(g.generujMuza("001210/7887"));

        System.out.println("Generovanie PAV");
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println("Generovanie SPAV");
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());

        System.out.println("Generovanie dlhov");
        System.out.println(g.generujDlh());
        System.out.println(g.generujDlh());
        System.out.println(g.generujDlh());
        System.out.println(g.generujDlh());
        System.out.println(g.generujDlh());
        System.out.println(g.generujDlh());

        System.out.println("Generovanie pravidelnych platieb");
        System.out.println(g.generujTypPP());
        System.out.println(g.generujTypPP());

        System.out.println("DOMACNOST 3-2");
        System.out.println("Generovanie domacnosti");
        System.out.println(g.generujDomacnost());
        System.out.println("Generovanie osob");
        System.out.println(g.generujMuza("780628/6895"));
        System.out.println(g.generujZenu("685114/3156"));
        System.out.println("Generovanie PAV");
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println("Generovanie SPAV");
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println("Generovanie dlhov");
        System.out.println(g.generujDlh());
        System.out.println(g.generujDlh());
        System.out.println(g.generujDlh());
        System.out.println(g.generujDlh());
        System.out.println("Generovanie pravidelnych platieb");
        System.out.println(g.generujTypPP());

        System.out.println("DOMACNOST 4-1");
        System.out.println("Generovanie domacnosti");
        System.out.println(g.generujDomacnost());
        System.out.println("Generovanie osob");
        System.out.println(g.generujZenu("805712/8519"));
        System.out.println("Generovanie PAV");
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());

        System.out.println("Generovanie SPAV");
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println("Generovanie dlhov");
        System.out.println(g.generujDlh());
        System.out.println(g.generujDlh());
        System.out.println("Generovanie pravidelnych platieb");
        System.out.println(g.generujTypPP());

        System.out.println("DOMACNOST 5-5");
        System.out.println("Generovanie domacnosti");
        System.out.println(g.generujDomacnost());
        System.out.println("Generovanie osob");
        System.out.println(g.generujZenu("495503/618"));
        System.out.println(g.generujMuza("510218/721"));
        System.out.println(g.generujZenu("645617/0831"));
        System.out.println(g.generujMuza("780711/5789"));
        System.out.println(g.generujMuza("900515/3883"));
        System.out.println("Generovanie PAV");
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());


        System.out.println("Generovanie SPAV");
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println("Generovanie dlhov");
        System.out.println(g.generujDlh());
        System.out.println(g.generujDlh());
        System.out.println(g.generujDlh());
        System.out.println(g.generujDlh());
        System.out.println(g.generujDlh());
        System.out.println("Generovanie pravidelnych platieb");
        System.out.println(g.generujTypPP());
        System.out.println(g.generujTypPP());
        System.out.println(g.generujTypPP());

        System.out.println("DOMACNOST 6-1");
        System.out.println("Generovanie domacnosti");
        System.out.println(g.generujDomacnost());

        System.out.println("Generovanie osob");
        System.out.println(g.generujMuza("951013/4986"));
        System.out.println("Generovanie PAV");
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println("Generovanie SPAV");
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println("Generovanie dlhov");
        System.out.println(g.generujDlh());
        System.out.println(g.generujDlh());
        System.out.println(g.generujDlh());
        System.out.println(g.generujDlh());
        System.out.println("Generovanie pravidelnych platieb");
        System.out.println(g.generujTypPP());
        System.out.println(g.generujTypPP());
        System.out.println(g.generujTypPP());
        System.out.println(g.generujTypPP());
        System.out.println(g.generujTypPP());

        System.out.println("DOMACNOST 7-2");
        System.out.println("Generovanie domacnosti");
        System.out.println(g.generujDomacnost());

        System.out.println("Generovanie osob");
        System.out.println(g.generujMuza("830608/6536"));
        System.out.println(g.generujZenu("945521/6969"));
        System.out.println("Generovanie PAV");
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());

        System.out.println("Generovanie SPAV");
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println("Generovanie dlhov");
        System.out.println(g.generujDlh());
        System.out.println(g.generujDlh());
        System.out.println("Generovanie pravidelnych platieb");
        System.out.println(g.generujTypPP());
        System.out.println(g.generujTypPP());

        System.out.println("DOMACNOST 8-3");
        System.out.println("Generovanie domacnosti");
        System.out.println(g.generujDomacnost());

        System.out.println("Generovanie osob");
        System.out.println(g.generujZenu("896219/8949"));
        System.out.println(g.generujMuza("950920/5420"));
        System.out.println(g.generujZenu("055312/7058"));
        System.out.println("Generovanie PAV");
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());


        System.out.println("Generovanie SPAV");
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());

        System.out.println("Generovanie dlhov");
        System.out.println(g.generujDlh());
        System.out.println("Generovanie pravidelnych platieb");
        System.out.println(g.generujTypPP());
        System.out.println(g.generujTypPP());
        System.out.println(g.generujTypPP());

        System.out.println("DOMACNOST 9-2");
        System.out.println("Generovanie domacnosti");
        System.out.println(g.generujDomacnost());

        System.out.println("Generovanie osob");
        System.out.println(g.generujZenu("655903/0368"));
        System.out.println(g.generujMuza("781119/5953"));
        System.out.println("Generovanie PAV");
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println("Generovanie SPAV");
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println("Generovanie dlhov");
        System.out.println(g.generujDlh());
        System.out.println(g.generujDlh());
        System.out.println(g.generujDlh());
        System.out.println("Generovanie pravidelnych platieb");
        System.out.println(g.generujTypPP());
        System.out.println(g.generujTypPP());

        System.out.println("DOMACNOST 10-4");
        System.out.println("Generovanie domacnosti");
        System.out.println(g.generujDomacnost());

        System.out.println("Generovanie osob");
        System.out.println(g.generujZenu("476128/485"));
        System.out.println(g.generujMuza("490703/832"));
        System.out.println(g.generujZenu("655903/0368"));
        System.out.println(g.generujZenu("930820/3652"));
        System.out.println("Generovanie PAV");
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());


        System.out.println("Generovanie SPAV");
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println("Generovanie dlhov");
        System.out.println(g.generujDlh());
        System.out.println(g.generujDlh());
        System.out.println(g.generujDlh());
        System.out.println("Generovanie pravidelnych platieb");
        System.out.println(g.generujTypPP());
        System.out.println(g.generujTypPP());

        System.out.println("DOMACNOST 11-4");
        System.out.println("Generovanie domacnosti");
        System.out.println(g.generujDomacnost());

        System.out.println("Generovanie osob");
        System.out.println(g.generujZenu("605903/3618"));
        System.out.println(g.generujMuza("500114/228"));
        System.out.println(g.generujMuza("790615/5884"));
        System.out.println(g.generujMuza("780711/5789"));
        System.out.println("Generovanie PAV");
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());

        System.out.println("Generovanie SPAV");
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println("Generovanie dlhov");
        System.out.println(g.generujDlh());
        System.out.println(g.generujDlh());
        System.out.println("Generovanie pravidelnych platieb");
        System.out.println(g.generujTypPP());

        System.out.println("DOMACNOST 12-5");
        System.out.println("Generovanie domacnosti");
        System.out.println(g.generujDomacnost());

        System.out.println("Generovanie osob");
        System.out.println(g.generujZenu("435208/911"));
        System.out.println(g.generujMuza("500114/228"));
        System.out.println(g.generujZenu("775711/1560"));
        System.out.println(g.generujMuza("710113/8099"));
        System.out.println(g.generujZenu("055312/7058"));
        System.out.println("Generovanie PAV");
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());

        System.out.println("Generovanie SPAV");
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());

        System.out.println("Generovanie dlhov");
        System.out.println(g.generujDlh());
        System.out.println(g.generujDlh());
        System.out.println("Generovanie pravidelnych platieb");
        System.out.println(g.generujTypPP());
        System.out.println(g.generujTypPP());
        System.out.println(g.generujTypPP());
        System.out.println(g.generujTypPP());


        System.out.println("DOMACNOST 13-2");
        System.out.println("Generovanie domacnosti");
        System.out.println(g.generujDomacnost());

        System.out.println("Generovanie osob");
        System.out.println(g.generujZenu("636220/4068"));
        System.out.println(g.generujMuza("830716/2028"));
        System.out.println("Generovanie PAV");
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println("Generovanie SPAV");
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println("Generovanie dlhov");
        System.out.println(g.generujDlh());
        System.out.println(g.generujDlh());
        System.out.println("Generovanie pravidelnych platieb");
        System.out.println(g.generujTypPP());
        System.out.println(g.generujTypPP());

        System.out.println("DOMACNOST 14-3");
        System.out.println("Generovanie domacnosti");
        System.out.println(g.generujDomacnost());

        System.out.println("Generovanie osob");
        System.out.println(g.generujZenu("485123/736"));
        System.out.println(g.generujMuza("520503/567"));
        System.out.println(g.generujMuza("060310/3677"));
        System.out.println("Generovanie PAV");
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());

        System.out.println("Generovanie SPAV");
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println("Generovanie dlhov");
        System.out.println(g.generujDlh());
        System.out.println("Generovanie pravidelnych platieb");
        System.out.println(g.generujTypPP());
        System.out.println(g.generujTypPP());

        System.out.println("DOMACNOST 15-1");
        System.out.println("Generovanie domacnosti");
        System.out.println(g.generujDomacnost());

        System.out.println("Generovanie osob");
        System.out.println(g.generujZenu("485206/640"));
        System.out.println("Generovanie PAV");
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println(g.generujPav());
        System.out.println("Generovanie SPAV");
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());
        System.out.println(g.generujSpav());

        System.out.println("Generovanie dlhov");
        System.out.println(g.generujDlh());
        System.out.println(g.generujDlh());
        System.out.println("Generovanie pravidelnych platieb");
        System.out.println(g.generujTypPP());
        System.out.println(g.generujTypPP());


    }
}
